### ISSUE TITLE
Feature Request: On Pushes

### ISSUE THREAD

**Issue by youngbrioche** [calibreapp/image-actions#16]
It'd be awesome if this would work in a non-pull-request workflow, e.g. for simple pushes to master. Just tried it, didn't work.

**Comment by benschwarz** [comment]
Hey @youngbrioche I get what you mean. Unfortunately committing directly to master poses to much risk as for many master is a deployment target to production. 

There's no way I'd want to make it easy to break someones images without them having a record of it that could be easily found and reversed. 

Because this action will run on all images, even if a single commit to master isn't worth PRing, the images will be corrected on the next PR. That way they'll eventually be compressed and will make their way to master. … At least, that's how I like to think about the flow. 

Will that work for your purposes?

**Comment by youngbrioche** [comment]
Thanks!
