### ISSUE TITLE
[Feature Request] Add support for SVGs

### ISSUE THREAD

**Issue by cadamsdev** [calibreapp/image-actions#295]
### What problem would this feature solve?

This GitHub action compresses "images" but doesn't support compressing "SVGs" which is a common image format used on websites.

### Describe the solution you’d like to see

Add support for compressing / optimizing SVG files.

I see there was an issue opened up a long time ago regarding this.
https://github.com/calibreapp/image-actions/issues/7

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by benschwarz** [comment]
Hey @cadamsdev, thanks for posting. 

I re-reviewed conversation in #7. I still believe SVG optimisation should be deliberately enabled, or enabled for certain file paths. Generally speaking, the discussion in #7 still seems relevant. 

If you were interested in picking up this task, I'd recommend taking that onboard first 👍 I'll be happy to discuss with you here (or on PR review) to get it shipped. 

One detail of note is that we're close to flipping this github action to use JS runtime directly (rather than build a docker image). I don't think any shared libraries will be required, but thought it was worth mentioning anyway!

**Comment by cadamsdev** [comment]
Closing issue, no longer needed.
