### ISSUE TITLE
10+ minutes to build

### ISSUE THREAD

**Issue by Logerfo** [calibreapp/image-actions#5]
Is the huge building time known and intentional? I couldn't manage to get a build briefer than 10 minutes in GitHub Actions.

**Comment by benschwarz** [comment]
Thanks for logging this @Logerfo.

I'd written this a number of months ago but was put off releasing it because the rollout for GitHub actions had been so poor. During that time GitHub changed some things about how actions are handled.

The result of that was that Docker containers/images were no longer cached at all and required a rebuild every time. 

To address this, we now pre-build the image on Dockerhub, then reference that.  (See #5 for more info)

**Comment by Logerfo** [comment]
Why use docker at all, if you're using javascript? Building takes longer than actually running...

**Comment by benschwarz** [comment]
@Logerfo 

> Why use docker at all, if you're using javascript? Building takes longer than actually running...

As I pointed out in the last issue. **On the day that you used image-actions** GitHub had changed how docker images were cached. This meant that image-actions would be fully compiled from source before being run on your repository. 

In #6, I pre-built docker images and pushed them to Docker hub. If you follow the installation settings in `README.md` it'll give you the updated configuration that uses the pre-built docker images. Image-actions should run < 1 minute. 

--

Some additional context:

Docker is used because `libvips` must be built from source to include `mozjpeg`, which gives the most efficient image compression for jpeg images. The full uncached docker build for that will take around ~10 minutes. 

Because we're now pre-building the images as part of our release process, the time that you will wait now is to download the docker image to GitHub's actions servers. Generally that should be pretty quick.

**Comment by Logerfo** [comment]
Yes, I'm using the cached image since #6 and in fact takes less than a minute. But that's not my point.
![image](https://user-images.githubusercontent.com/19306384/67686055-debd9600-f974-11e9-8e6f-86113db14dac.png)
Running still is the quicker step.
I think you could create a release branch with **everything** needed to run: `libvips`, `node_modules` and whatnot. In order to do that, you should remove those stuff from `.gitignore` and push them to the release branch. The current workflow with docker does not need to be deprecated.
If you don't know what I mean, check out what I've done for [gitflow-action](https://github.com/Logerfo/gitflow-action) and [newline-action](https://github.com/Logerfo/newline-action).

**Comment by benschwarz** [comment]
@Logerfo In order for this code to run, it requires `libvips` to be built from source to include support for `mozjpeg`. It is a requirement. We can't skip that.

**Comment by Logerfo** [comment]
I'm not asking for it to be skipped, but for it to be done once at deploying phase instead of always at building phase.

**Comment by benschwarz** [comment]
> it to be done once at deploying phase instead of always at building phase.

It is. The 29 seconds of runtime from your screenshot is from the Docker pull. That's how long that takes. There's nothing I can do about that.

**Comment by Logerfo** [comment]
I think you don't need to use docker at all. Instead, you could use a release branch with the node modules and libvips. The workflow configuration would them refer to node instead of docker.

**Comment by benschwarz** [comment]
@Logerfo You've ignored what I've said a number of times now.

 **We must compile libvips with support for mozjpeg**. 

I'm locking this thread. Feel free to open another one if there's an action that can be actually taken.
